spring:
  profiles:
    active: dev
  session:
    store-type: none
  thymeleaf:
  #缓存禁用
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8

mybatis:
  type-aliases-package: com.majy.scoremanager.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

server:
  tomcat:
    accesslog:
      enabled: true